### ISSUE TITLE
Add privacy settings

### ISSUE THREAD

**Issue by Jokauppi** [TKOaly/rv-backend#77]
Current RV allows the user to choose whether to show their history to everyone with or without their username or not show history to others at all.

This doesn't yet have an endpoint in the new backend.

#### Todo
- [x] Create database entry/migration for privacy info
- [x] Create endpoint for getting privacy setting for user
- [x] Create endpoint for changing privacy setting

**Comment by Jokauppi** [comment]
This is only needed if we implement a leaderboard into the user terminal. I think it isn't a feature required for an MVP so this is not a priority and should be done later if necessary

**Comment by ArktinenKarpalo** [comment]
This is simple to add, there are places like https://gurula.network/ for which the information could be of use.

**Comment by ArktinenKarpalo** [comment]
see https://github.com/TKOaly/rv-backend/pull/147/commits/1ba4a54885b0dc070595fdeeae7ca37a6db2ee73
