### ISSUE TITLE
Configure build and production pipeline

### ISSUE THREAD

**Issue by Jokauppi** [TKOaly/rv-backend#94]
These should be the current instructions for creating a new application https://github.com/TKOaly/service-wiki/wiki/New-web-application. 

### to-do list:
- [ ] Enable org secrets
- [ ] Add Docker image push action
- [ ] Create k8s config with secrets
- [ ] Add app in argocd
- [ ] Apache config
- [ ] Create DNS entry
- [ ] Update certificate
